services:
  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: nest
      MYSQL_PASSWORD: nestpass
    ports:
      - '3307:3306'
